#include <QtGlobal>
// Automatically generated by extract_strings.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *bitcoin_strings[] = {
QT_TRANSLATE_NOOP("yacoin-core", ""
"%s, you must set a rpcpassword in the configuration file:\n"
" %s\n"
"It is recommended you use the following random password:\n"
"rpcuser=yacoinrpc\n"
"rpcpassword=%s\n"
"(you do not need to remember this password)\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions.\n"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Acceptable ciphers (default: TLSv1+HIGH:!SSLv2:!aNULL:!eNULL:!AH:!3DES:"
"@STRENGTH)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"An error occurred while setting up the RPC port %u for listening on IPv4: %s"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"An error occurred while setting up the RPC port %u for listening on IPv6, "
"falling back to IPv4: %s"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Cannot obtain a lock on data directory %s.  Yacoin is probably already "
"running."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Detach block and address databases. Increases shutdown time (default: 0)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error initializing database environment %s! To recover, BACKUP THAT "
"DIRECTORY, then remove everything from it except for wallet.dat."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error: The transaction was rejected.  This might happen if some of the coins "
"in your wallet were already spent, such as if you used a copy of wallet.dat "
"and coins were spent in the copy but not marked as spent here."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error: This transaction requires a transaction fee of at least %s because of "
"its amount, complexity, or use of recently received funds  "),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error: Wallet unlocked for block minting only, unable to create transaction."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Execute command when the best block changes (%s in cmd is replaced by block "
"hash)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Listen for JSON-RPC connections on <port> (default: 7687 or testnet: 17687)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: "
"86400)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Set maximum size of high-priority/low-fee transactions in bytes (default: "
"27000)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Unable to bind to %s on this computer. Yacoin is probably already running."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: -paytxfee is set very high! This is the transaction fee you will "
"pay if you send a transaction."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: Please check that your computer's date and time are correct! If "
"your clock is wrong Yacoin will not work properly."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: error reading wallet.dat! All keys read correctly, but transaction "
"data or address book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: wallet.dat corrupt, data salvaged! Original wallet.dat saved as "
"wallet.{timestamp}.bak in %s; if your balance or transactions are incorrect "
"you should restore from a backup."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"You must set rpcpassword=<password> in the configuration file:\n"
"%s\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions."),
QT_TRANSLATE_NOOP("yacoin-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("yacoin-core", "Accept connections from outside (default: 1 if no -proxy or -connect)"),
QT_TRANSLATE_NOOP("yacoin-core", "Add a node to connect to and attempt to keep the connection open"),
QT_TRANSLATE_NOOP("yacoin-core", "Allow DNS lookups for -addnode, -seednode and -connect"),
QT_TRANSLATE_NOOP("yacoin-core", "Allow JSON-RPC connections from specified IP address"),
QT_TRANSLATE_NOOP("yacoin-core", "Attempt to recover private keys from a corrupt wallet.dat"),
QT_TRANSLATE_NOOP("yacoin-core", "Bind to given address. Use [host]:port notation for IPv6"),
QT_TRANSLATE_NOOP("yacoin-core", "Block creation options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot initialize keypool"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot resolve -bind address: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot resolve -externalip address: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot write default address"),
QT_TRANSLATE_NOOP("yacoin-core", "Connect only to the specified node(s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Connect through socks proxy"),
QT_TRANSLATE_NOOP("yacoin-core", "Connect to a node to retrieve peer addresses, and disconnect"),
QT_TRANSLATE_NOOP("yacoin-core", "Discover own IP address (default: 1 when listening and no -externalip)"),
QT_TRANSLATE_NOOP("yacoin-core", "Done loading"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading blkindex.dat"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading wallet.dat"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading wallet.dat: Wallet corrupted"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading wallet.dat: Wallet requires newer version of Yacoin"),
QT_TRANSLATE_NOOP("yacoin-core", "Error"),
QT_TRANSLATE_NOOP("yacoin-core", "Error: Transaction creation failed  "),
QT_TRANSLATE_NOOP("yacoin-core", "Error: Wallet locked, unable to create transaction  "),
QT_TRANSLATE_NOOP("yacoin-core", "Error: could not start node"),
QT_TRANSLATE_NOOP("yacoin-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("yacoin-core", "Fee per KB to add to transactions you send"),
QT_TRANSLATE_NOOP("yacoin-core", "Find peers using DNS lookup (default: 0)"),
QT_TRANSLATE_NOOP("yacoin-core", "Find peers using internet relay chat (default: 1)"),
QT_TRANSLATE_NOOP("yacoin-core", "Get help for a command"),
QT_TRANSLATE_NOOP("yacoin-core", "How many blocks to check at startup (default: 750, 0 = all)"),
QT_TRANSLATE_NOOP("yacoin-core", "How thorough the block verification is (0-6, default: 1)"),
QT_TRANSLATE_NOOP("yacoin-core", "Importing blockchain data file."),
QT_TRANSLATE_NOOP("yacoin-core", "Importing bootstrap blockchain data file."),
QT_TRANSLATE_NOOP("yacoin-core", "Imports blocks from external blk000?.dat file"),
QT_TRANSLATE_NOOP("yacoin-core", "Insufficient funds"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid -proxy address: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid -tor address: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount for -paytxfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount for -reservebalance=<amount>"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount"),
QT_TRANSLATE_NOOP("yacoin-core", "List commands"),
QT_TRANSLATE_NOOP("yacoin-core", "Listen for connections on <port> (default: 7688 or testnet: 17688)"),
QT_TRANSLATE_NOOP("yacoin-core", "Loading addresses..."),
QT_TRANSLATE_NOOP("yacoin-core", "Loading block index..."),
QT_TRANSLATE_NOOP("yacoin-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("yacoin-core", "Maintain at most <n> connections to peers (default: 125)"),
QT_TRANSLATE_NOOP("yacoin-core", "Maximum per-connection receive buffer, <n>*1000 bytes (default: 5000)"),
QT_TRANSLATE_NOOP("yacoin-core", "Maximum per-connection send buffer, <n>*1000 bytes (default: 1000)"),
QT_TRANSLATE_NOOP("yacoin-core", "Yacoin version"),
QT_TRANSLATE_NOOP("yacoin-core", "Yacoin"),
QT_TRANSLATE_NOOP("yacoin-core", "Only connect to nodes in network <net> (IPv4, IPv6 or Tor)"),
QT_TRANSLATE_NOOP("yacoin-core", "Options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Output extra debugging information. Implies all other -debug* options"),
QT_TRANSLATE_NOOP("yacoin-core", "Output extra network debugging information"),
QT_TRANSLATE_NOOP("yacoin-core", "Password for JSON-RPC connections"),
QT_TRANSLATE_NOOP("yacoin-core", "Prepend debug output with timestamp"),
QT_TRANSLATE_NOOP("yacoin-core", "Rescan the block chain for missing wallet transactions"),
QT_TRANSLATE_NOOP("yacoin-core", "Rescanning..."),
QT_TRANSLATE_NOOP("yacoin-core", "Run in the background as a daemon and accept commands"),
QT_TRANSLATE_NOOP("yacoin-core", "SSL options: (see the Bitcoin Wiki for SSL setup instructions)"),
QT_TRANSLATE_NOOP("yacoin-core", "Select the version of socks proxy to use (4-5, default: 5)"),
QT_TRANSLATE_NOOP("yacoin-core", "Send command to -server or yacoind"),
QT_TRANSLATE_NOOP("yacoin-core", "Send commands to node running on <ip> (default: 127.0.0.1)"),
QT_TRANSLATE_NOOP("yacoin-core", "Send trace/debug info to console instead of debug.log file"),
QT_TRANSLATE_NOOP("yacoin-core", "Send trace/debug info to debugger"),
QT_TRANSLATE_NOOP("yacoin-core", "Sending..."),
QT_TRANSLATE_NOOP("yacoin-core", "Server certificate file (default: server.cert)"),
QT_TRANSLATE_NOOP("yacoin-core", "Server private key (default: server.pem)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set database cache size in megabytes (default: 25)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set database disk log size in megabytes (default: 100)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set key pool size to <n> (default: 100)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set maximum block size in bytes (default: 250000)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set minimum block size in bytes (default: 0)"),
QT_TRANSLATE_NOOP("yacoin-core", "Shrink debug.log file on client startup (default: 1 when no -debug)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify configuration file (default: yacoin.conf)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify connection timeout in milliseconds (default: 5000)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify data directory"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify pid file (default: yacoind.pid)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify your own public address"),
QT_TRANSLATE_NOOP("yacoin-core", "This help message"),
QT_TRANSLATE_NOOP("yacoin-core", "Threshold for disconnecting misbehaving peers (default: 100)"),
QT_TRANSLATE_NOOP("yacoin-core", "To use the %s option"),
QT_TRANSLATE_NOOP("yacoin-core", "Unable to bind to %s on this computer (bind returned error %d, %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Unable to sign checkpoint, wrong checkpointkey?\n"),
QT_TRANSLATE_NOOP("yacoin-core", "Unknown -socks proxy version requested: %i"),
QT_TRANSLATE_NOOP("yacoin-core", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Upgrade wallet to latest format"),
QT_TRANSLATE_NOOP("yacoin-core", "Usage:"),
QT_TRANSLATE_NOOP("yacoin-core", "Use OpenSSL (https) for JSON-RPC connections"),
QT_TRANSLATE_NOOP("yacoin-core", "Use UPnP to map the listening port (default: 0)"),
QT_TRANSLATE_NOOP("yacoin-core", "Use UPnP to map the listening port (default: 1 when listening)"),
QT_TRANSLATE_NOOP("yacoin-core", "Use proxy to reach tor hidden services (default: same as -proxy)"),
QT_TRANSLATE_NOOP("yacoin-core", "Use the test network"),
QT_TRANSLATE_NOOP("yacoin-core", "Username for JSON-RPC connections"),
QT_TRANSLATE_NOOP("yacoin-core", "Verifying database integrity..."),
QT_TRANSLATE_NOOP("yacoin-core", "Wallet needed to be rewritten: restart Yacoin to complete"),
QT_TRANSLATE_NOOP("yacoin-core", "Warning: Disk space is low!"),
QT_TRANSLATE_NOOP("yacoin-core", "Warning: This version is obsolete, upgrade required!"),
QT_TRANSLATE_NOOP("yacoin-core", "wallet.dat corrupt, salvage failed"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify wallet file (within data directory)"),
QT_TRANSLATE_NOOP("yacoin-core", "Use in-memory logging for block index database (default: 1)"),
QT_TRANSLATE_NOOP("yacoin-core", "Find peers using DNS lookup (default: 1)"),
QT_TRANSLATE_NOOP("yacoin-core", "Sync checkpoints policy (default: strict)"),
QT_TRANSLATE_NOOP("yacoin-core", "Execute command when a wallet transaction changes (%s in cmd is replaced by TxID)"),
QT_TRANSLATE_NOOP("yacoin-core", "Require a confirmations for change (default: 0)"),
QT_TRANSLATE_NOOP("yacoin-core", "Enforce transaction scripts to use canonical PUSH operators (default: 1)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set the number of script verification threads (1-16, 0=auto, default: 0)"),
QT_TRANSLATE_NOOP("yacoin-core", "When creating transactions, ignore inputs with value less than this (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "The %s developers"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"(1 = keep tx meta data e.g. account owner and payment request information, 2 "
"= drop tx meta data)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"-maxtxfee is set very high! Fees this large could be paid on a single "
"transaction."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"A fee rate (in %s/kB) that will be used when fee estimation has insufficient "
"data (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Accept relayed transactions received from whitelisted peers even when not "
"relaying transactions (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Allow JSON-RPC connections from specified source. Valid for <ip> are a "
"single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or "
"a network/CIDR (e.g. 1.2.3.4/24). This option can be specified multiple times"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Bind to given address and always listen on it. Use [host]:port notation for "
"IPv6"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Bind to given address and whitelist peers connecting to it. Use [host]:port "
"notation for IPv6"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Bind to given address to listen for JSON-RPC connections. This option is "
"ignored unless -rpcallowip is also passed. Port is optional and overrides -"
"rpcport. Use [host]:port notation for IPv6. This option can be specified "
"multiple times (default: 127.0.0.1 and ::1 i.e., localhost, or if -"
"rpcallowip has been specified, 0.0.0.0 and :: i.e., all addresses)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Connect only to the specified node(s); -connect=0 disables automatic "
"connections"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Create new files with system default permissions, instead of umask 077 (only "
"effective with disabled wallet functionality)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Delete all wallet transactions and only recover those parts of the "
"blockchain through -rescan on startup"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Discover own IP addresses (default: 1 when listening and no -externalip or -"
"proxy)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Distributed under the MIT software license, see the accompanying file %s or "
"%s"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Do not keep transactions in the mempool longer than <n> hours (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Equivalent bytes per sigop in transactions for relay and mining (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error loading %s: You can't enable HD on an already existing non-HD wallet"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error loading wallet %s. -wallet parameter must only specify a filename (not "
"a path)."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error reading %s! All keys read correctly, but transaction data or address "
"book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Error: Listening for incoming connections failed (listen returned error %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Exclude debugging information for a category. Can be used in conjunction "
"with -debug=1 to output debug logs for all categories except one or more "
"specified categories."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Execute command when a relevant alert is received or we see a really long "
"fork (%s in cmd is replaced by message)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Execute command when a wallet transaction changes (%s in cmd is replaced by "
"TxID)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Execute command when the best block changes (%s in cmd is replaced by block "
"hash)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Extra transactions to keep in memory for compact block reconstructions "
"(default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Fees (in %s/kB) smaller than this are considered zero fee for relaying, "
"mining and transaction creation (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Fees (in %s/kB) smaller than this are considered zero fee for transaction "
"creation (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Force relay of transactions from whitelisted peers even if they violate "
"local relay policy (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"How thorough the block verification of -checkblocks is (0-4, default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"If <category> is not supplied or if <category> = 1, output all debugging "
"information."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"If paytxfee is not set, include enough fee so transactions begin "
"confirmation on average within n blocks (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"If this block is in the chain assume that it and its ancestors are valid and "
"potentially skip their script verification (0 to verify all, default: %s, "
"testnet: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Invalid amount for -maxtxfee=<amount>: '%s' (must be at least the minrelay "
"fee of %s to prevent stuck transactions)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Maintain a full transaction index, used by the getrawtransaction rpc call "
"(default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Maximum allowed median peer time offset adjustment. Local perspective of "
"time may be influenced by peers forward or backward by this amount. "
"(default: %u seconds)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Maximum size of data in data carrier transactions we relay and mine "
"(default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Maximum total fees (in %s) to use in a single wallet transaction or raw "
"transaction; setting this too low may abort large transactions (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Output debugging information (default: %u, supplying <category> is optional)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Please check that your computer's date and time are correct! If your clock "
"is wrong, %s will not work properly."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Please contribute if you find %s useful. Visit %s for further information "
"about the software."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Prune configured below the minimum of %d MiB.  Please use a higher number."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Prune: last wallet synchronisation goes beyond pruned data. You need to -"
"reindex (download the whole blockchain again in case of pruned node)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Query for peer addresses via DNS lookup, if low on addresses (default: 1 "
"unless -connect used)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Randomize credentials for every proxy connection. This enables Tor stream "
"isolation (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Reduce storage requirements by enabling pruning (deleting) of old blocks. "
"This allows the pruneblockchain RPC to be called to delete specific blocks, "
"and enables automatic pruning of old blocks if a target size in MiB is "
"provided. This mode is incompatible with -txindex and -rescan. Warning: "
"Reverting this setting requires re-downloading the entire blockchain. "
"(default: 0 = disable pruning blocks, 1 = allow manual pruning via RPC, >%u "
"= automatically prune block files to stay under the specified target size in "
"MiB)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Rescans are not possible in pruned mode. You will need to use -reindex which "
"will download the whole blockchain again."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Set lowest fee rate (in %s/kB) for transactions to be included in block "
"creation. (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Set the number of script verification threads (%u to %d, 0 = auto, <0 = "
"leave that many cores free, default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Sets the serialization of raw transaction or block hex returned in non-"
"verbose mode, non-segwit(0) or segwit(1) (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Support filtering of blocks and transaction with bloom filters (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"The block database contains a block which appears to be from the future. "
"This may be due to your computer's date and time being set incorrectly. Only "
"rebuild the block database if you are sure that your computer's date and "
"time are correct"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"The fee rate (in %s/kB) that indicates your tolerance for discarding change "
"by adding it to the fee (default: %s). Note: An output is discarded if it is "
"dust at this rate, but we will always discard up to the dust relay fee and a "
"discard fee above that is limited by the fee estimate for the longest target"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"The transaction amount is too small to send after the fee has been deducted"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"This is a pre-release test build - use at your own risk - do not use for "
"mining or merchant applications"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"This is the transaction fee you may discard if change is smaller than dust "
"at this level"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"This is the transaction fee you may pay when fee estimates are not available."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"This product includes software developed by the OpenSSL Project for use in "
"the OpenSSL Toolkit %s and cryptographic software written by Eric Young and "
"UPnP software written by Thomas Bernard."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Total length of network version string (%i) exceeds maximum length (%i). "
"Reduce the number or size of uacomments."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Tries to keep outbound traffic under the given target (in MiB per 24h), 0 = "
"no limit (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Unable to replay blocks. You will need to rebuild the database using -"
"reindex-chainstate."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Unable to rewind the database to a pre-fork state. You will need to "
"redownload the blockchain"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Unsupported argument -socks found. Setting SOCKS version isn't possible "
"anymore, only SOCKS5 proxies are supported."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Unsupported argument -whitelistalwaysrelay ignored, use -whitelistrelay and/"
"or -whitelistforcerelay."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Use UPnP to map the listening port (default: 1 when listening and no -proxy)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Use hierarchical deterministic key generation (HD) after BIP32. Only has "
"effect during wallet creation/first start"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Use separate SOCKS5 proxy to reach peers via Tor hidden services (default: "
"%s)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Username and hashed password for JSON-RPC connections. The field <userpw> "
"comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is "
"included in share/rpcuser. The client then connects normally using the "
"rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This option can "
"be specified multiple times"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Wallet will not create transactions that violate mempool chain limits "
"(default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: The network does not appear to fully agree! Some miners appear to "
"be experiencing issues."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: Unknown block versions being mined! It's possible unknown rules are "
"in effect"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: Wallet file corrupt, data salvaged! Original %s saved as %s in %s; "
"if your balance or transactions are incorrect you should restore from a "
"backup."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Warning: We do not appear to fully agree with our peers! You may need to "
"upgrade, or other nodes may need to upgrade."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Whether to save the mempool on shutdown and load on restart (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Whitelist peers connecting from the given IP address (e.g. 1.2.3.4) or CIDR "
"notated network (e.g. 1.2.3.0/24). Can be specified multiple times."),
QT_TRANSLATE_NOOP("yacoin-core", ""
"Whitelisted peers cannot be DoS banned and their transactions are always "
"relayed, even if they are already in the mempool, useful e.g. for a gateway"),
QT_TRANSLATE_NOOP("yacoin-core", ""
"You need to rebuild the database using -reindex to go back to unpruned "
"mode.  This will redownload the entire blockchain"),
QT_TRANSLATE_NOOP("yacoin-core", "%d of last 100 blocks have unexpected version"),
QT_TRANSLATE_NOOP("yacoin-core", "%s corrupt, salvage failed"),
QT_TRANSLATE_NOOP("yacoin-core", "%s is set very high!"),
QT_TRANSLATE_NOOP("yacoin-core", "(default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "(default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "(press q to shutdown and continue later)"),
QT_TRANSLATE_NOOP("yacoin-core", "-maxmempool must be at least %d MB"),
QT_TRANSLATE_NOOP("yacoin-core", "<category> can be:"),
QT_TRANSLATE_NOOP("yacoin-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("yacoin-core", "Accept connections from outside (default: 1 if no -proxy or -connect)"),
QT_TRANSLATE_NOOP("yacoin-core", "Accept public REST requests (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Add a node to connect to and attempt to keep the connection open"),
QT_TRANSLATE_NOOP("yacoin-core", "Allow DNS lookups for -addnode, -seednode and -connect"),
QT_TRANSLATE_NOOP("yacoin-core", "Always query for peer addresses via DNS lookup (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Append comment to the user agent string"),
QT_TRANSLATE_NOOP("yacoin-core", "Attempt to recover private keys from a corrupt wallet on startup"),
QT_TRANSLATE_NOOP("yacoin-core", "Automatically create Tor hidden service (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", "Block creation options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot resolve -%s address: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Cannot write default address"),
QT_TRANSLATE_NOOP("yacoin-core", "Chain selection options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Change index out of range"),
QT_TRANSLATE_NOOP("yacoin-core", "Connect through SOCKS5 proxy"),
QT_TRANSLATE_NOOP("yacoin-core", "Connect to a node to retrieve peer addresses, and disconnect"),
QT_TRANSLATE_NOOP("yacoin-core", "Connection options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Copyright (C) %i-%i"),
QT_TRANSLATE_NOOP("yacoin-core", "Corrupted block database detected"),
QT_TRANSLATE_NOOP("yacoin-core", "Debugging/Testing options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Do not load the wallet and disable wallet RPC calls"),
QT_TRANSLATE_NOOP("yacoin-core", "Do you want to rebuild the block database now?"),
QT_TRANSLATE_NOOP("yacoin-core", "Done loading"),
QT_TRANSLATE_NOOP("yacoin-core", "Enable publish hash block in <address>"),
QT_TRANSLATE_NOOP("yacoin-core", "Enable publish hash transaction in <address>"),
QT_TRANSLATE_NOOP("yacoin-core", "Enable publish raw block in <address>"),
QT_TRANSLATE_NOOP("yacoin-core", "Enable publish raw transaction in <address>"),
QT_TRANSLATE_NOOP("yacoin-core", "Enable transaction replacement in the memory pool (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Error initializing block database"),
QT_TRANSLATE_NOOP("yacoin-core", "Error initializing wallet database environment %s!"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading %s"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading %s: Wallet corrupted"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading %s: Wallet requires newer version of %s"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading %s: You can't disable HD on an already existing HD wallet"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading block database"),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading wallet %s. -wallet filename must be a regular file."),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading wallet %s. Duplicate -wallet filename specified."),
QT_TRANSLATE_NOOP("yacoin-core", "Error loading wallet %s. Invalid characters in -wallet filename."),
QT_TRANSLATE_NOOP("yacoin-core", "Error opening block database"),
QT_TRANSLATE_NOOP("yacoin-core", "Error reading from database, shutting down."),
QT_TRANSLATE_NOOP("yacoin-core", "Error upgrading chainstate database"),
QT_TRANSLATE_NOOP("yacoin-core", "Error"),
QT_TRANSLATE_NOOP("yacoin-core", "Error: A fatal internal error occurred, see debug.log for details"),
QT_TRANSLATE_NOOP("yacoin-core", "Error: Disk space is low!"),
QT_TRANSLATE_NOOP("yacoin-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("yacoin-core", "Fee (in %s/kB) to add to transactions you send (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "How many blocks to check at startup (default: %u, 0 = all)"),
QT_TRANSLATE_NOOP("yacoin-core", "Importing..."),
QT_TRANSLATE_NOOP("yacoin-core", "Imports blocks from external blk000??.dat file on startup"),
QT_TRANSLATE_NOOP("yacoin-core", "Include IP addresses in debug output (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Incorrect or no genesis block found. Wrong datadir for network?"),
QT_TRANSLATE_NOOP("yacoin-core", "Information"),
QT_TRANSLATE_NOOP("yacoin-core", "Initialization sanity check failed. %s is shutting down."),
QT_TRANSLATE_NOOP("yacoin-core", "Insufficient funds"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid -onion address or hostname: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid -proxy address or hostname: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount for -%s=<amount>: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount for -discardfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount for -fallbackfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid amount for -paytxfee=<amount>: '%s' (must be at least %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Invalid netmask specified in -whitelist: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Keep at most <n> unconnectable transactions in memory (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Keep the transaction memory pool below <n> megabytes (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Keypool ran out, please call keypoolrefill first"),
QT_TRANSLATE_NOOP("yacoin-core", "Listen for JSON-RPC connections on <port> (default: %u or testnet: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Listen for connections on <port> (default: %u or testnet: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Loading P2P addresses..."),
QT_TRANSLATE_NOOP("yacoin-core", "Loading banlist..."),
QT_TRANSLATE_NOOP("yacoin-core", "Loading block index..."),
QT_TRANSLATE_NOOP("yacoin-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("yacoin-core", "Location of the auth cookie (default: data dir)"),
QT_TRANSLATE_NOOP("yacoin-core", "Maintain at most <n> connections to peers (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Make the wallet broadcast transactions"),
QT_TRANSLATE_NOOP("yacoin-core", "Maximum per-connection receive buffer, <n>*1000 bytes (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Maximum per-connection send buffer, <n>*1000 bytes (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Need to specify a port with -whitebind: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Node relay options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Not enough file descriptors available."),
QT_TRANSLATE_NOOP("yacoin-core", "Only connect to nodes in network <net> (ipv4, ipv6 or onion)"),
QT_TRANSLATE_NOOP("yacoin-core", "Options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Password for JSON-RPC connections"),
QT_TRANSLATE_NOOP("yacoin-core", "Prepend debug output with timestamp (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Print this help message and exit"),
QT_TRANSLATE_NOOP("yacoin-core", "Print version and exit"),
QT_TRANSLATE_NOOP("yacoin-core", "Prune cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("yacoin-core", "Prune mode is incompatible with -txindex."),
QT_TRANSLATE_NOOP("yacoin-core", "Pruning blockstore..."),
QT_TRANSLATE_NOOP("yacoin-core", "RPC server options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Rebuild chain state and block index from the blk*.dat files on disk"),
QT_TRANSLATE_NOOP("yacoin-core", "Rebuild chain state from the currently indexed blocks"),
QT_TRANSLATE_NOOP("yacoin-core", "Reducing -maxconnections from %d to %d, because of system limitations."),
QT_TRANSLATE_NOOP("yacoin-core", "Relay and mine data carrier transactions (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Relay non-P2SH multisig (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Replaying blocks..."),
QT_TRANSLATE_NOOP("yacoin-core", "Rescan the block chain for missing wallet transactions on startup"),
QT_TRANSLATE_NOOP("yacoin-core", "Rescanning..."),
QT_TRANSLATE_NOOP("yacoin-core", "Rewinding blocks..."),
QT_TRANSLATE_NOOP("yacoin-core", "Run in the background as a daemon and accept commands"),
QT_TRANSLATE_NOOP("yacoin-core", "Send trace/debug info to console instead of debug.log file"),
QT_TRANSLATE_NOOP("yacoin-core", "Send transactions with full-RBF opt-in enabled (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set database cache size in megabytes (%d to %d, default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set key pool size to <n> (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set maximum BIP141 block weight (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set maximum block size in bytes (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", "Set the number of threads to service RPC calls (default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", "Show all debugging options (usage: --help -help-debug)"),
QT_TRANSLATE_NOOP("yacoin-core", "Shrink debug.log file on client startup (default: 1 when no -debug)"),
QT_TRANSLATE_NOOP("yacoin-core", "Signing transaction failed"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify configuration file (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify connection timeout in milliseconds (minimum: 1, default: %d)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify data directory"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify pid file (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify wallet file (within data directory)"),
QT_TRANSLATE_NOOP("yacoin-core", "Specify your own public address"),
QT_TRANSLATE_NOOP("yacoin-core", "Spend unconfirmed change when sending transactions (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Starting network threads..."),
QT_TRANSLATE_NOOP("yacoin-core", "The source code is available from %s."),
QT_TRANSLATE_NOOP("yacoin-core", "The transaction amount is too small to pay the fee"),
QT_TRANSLATE_NOOP("yacoin-core", "The wallet will avoid paying less than the minimum relay fee."),
QT_TRANSLATE_NOOP("yacoin-core", "This is experimental software."),
QT_TRANSLATE_NOOP("yacoin-core", "This is the minimum transaction fee you pay on every transaction."),
QT_TRANSLATE_NOOP("yacoin-core", "This is the transaction fee you will pay if you send a transaction."),
QT_TRANSLATE_NOOP("yacoin-core", "Threshold for disconnecting misbehaving peers (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Tor control port password (default: empty)"),
QT_TRANSLATE_NOOP("yacoin-core", "Tor control port to use if onion listening enabled (default: %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction amount too small"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction amounts must not be negative"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction fee and change calculation failed"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction has too long of a mempool chain"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction must have at least one recipient"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction too large for fee policy"),
QT_TRANSLATE_NOOP("yacoin-core", "Transaction too large"),
QT_TRANSLATE_NOOP("yacoin-core", "Unable to bind to %s on this computer (bind returned error %s)"),
QT_TRANSLATE_NOOP("yacoin-core", "Unable to bind to %s on this computer. %s is probably already running."),
QT_TRANSLATE_NOOP("yacoin-core", "Unable to start HTTP server. See debug log for details."),
QT_TRANSLATE_NOOP("yacoin-core", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("yacoin-core", "Unsupported argument -benchmark ignored, use -debug=bench."),
QT_TRANSLATE_NOOP("yacoin-core", "Unsupported argument -debugnet ignored, use -debug=net."),
QT_TRANSLATE_NOOP("yacoin-core", "Unsupported argument -tor found, use -onion."),
QT_TRANSLATE_NOOP("yacoin-core", "Unsupported logging category %s=%s."),
QT_TRANSLATE_NOOP("yacoin-core", "Upgrade wallet to latest format on startup"),
QT_TRANSLATE_NOOP("yacoin-core", "Upgrading UTXO database"),
QT_TRANSLATE_NOOP("yacoin-core", "Use UPnP to map the listening port (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "Use the test chain"),
QT_TRANSLATE_NOOP("yacoin-core", "User Agent comment (%s) contains unsafe characters."),
QT_TRANSLATE_NOOP("yacoin-core", "Username for JSON-RPC connections"),
QT_TRANSLATE_NOOP("yacoin-core", "Verifying blocks..."),
QT_TRANSLATE_NOOP("yacoin-core", "Verifying wallet(s)..."),
QT_TRANSLATE_NOOP("yacoin-core", "Wallet %s resides outside data directory %s"),
QT_TRANSLATE_NOOP("yacoin-core", "Wallet debugging/testing options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Wallet needed to be rewritten: restart %s to complete"),
QT_TRANSLATE_NOOP("yacoin-core", "Wallet options:"),
QT_TRANSLATE_NOOP("yacoin-core", "Warning"),
QT_TRANSLATE_NOOP("yacoin-core", "Warning: unknown new rules activated (versionbit %i)"),
QT_TRANSLATE_NOOP("yacoin-core", "Whether to operate in a blocks only mode (default: %u)"),
QT_TRANSLATE_NOOP("yacoin-core", "You need to rebuild the database using -reindex to change -txindex"),
QT_TRANSLATE_NOOP("yacoin-core", "Zapping all transactions from wallet..."),
QT_TRANSLATE_NOOP("yacoin-core", "ZeroMQ notification options:"),
};
